var items = [
    "Can I have a glass of water, please?",
    "Can you give me a ride to the airport?",
    "Can he play the guitar?",
    "Can she speak French fluently?",
    "Can it snow in April?",
    "Can we go for a walk in the park?",
    "Can you help me with my homework?",
    "Can they join us for dinner?",
    "Can I take a day off next week?",
    "Can you please turn off the TV?",
    "Can he come to the party with us?",
    "Can she wear sneakers to the office?",
    "Can it be done by tomorrow?",
    "Can we book a table for two, please?",
    "Can you lend me your pen for a minute?",
    "Can they bring their own drinks to the party?",
    "Can I have a refill of my coffee, please?",
    "Can you wait for me for a few minutes?",
    "Can he drive us to the beach?",
    "Can she take the day off for her doctor's appointment?",
    "Can it rain cats and dogs?",
    "Can we order some appetizers, please?",
    "Can you teach me how to cook this dish?",
    "Can they stay over for the weekend?",
    "Can I have a piece of cake, please?",
    "Can you please lower your voice?",
    "Can he have another serving of dessert?",
    "Can she bring her dog to the park?",
    "Can it be fixed easily?",
    "Can we reschedule the meeting for tomorrow?",
    "Can you lend me some money until next week?",
    "Can they play basketball with us?",
    "Can I use your phone for a quick call?",
    "Can you pick up some milk on your way home?",
    "Can he take the day off for personal reasons?",
    "Can she listen to music at work?",
    "Can it be returned for a refund?",
    "Can we have a moment of silence for the victims?",
    "Can you help me move this couch?",
    "Can they bring their kids to the party?",
    "Can I leave my coat here while I go out?",
    "Can you share your notes with me?",
    "Can he sit next to her in the theater?",
    "Can she wear a hat to the wedding?",
    "Can it be shipped internationally?",
    "Can we have some more bread, please?",
    "Can you remind me to call my mom tomorrow?",
    "Can they stay for the last game?",
    "Can I have a glass of wine, please?",
    "Can you wait for me at the entrance?",
    "Could you pass me the salt, please?",
    "Could I use your phone, if you don't mind?",
    "Could we have a moment alone, please?",
    "Could they come to the party, too?",
    "Could he fix the TV by himself?",
    "Could she speak French fluently when she was younger?",
    "Could it be possible to finish this project by tomorrow?",
    "Could you tell me the time, please?",
    "Could I ask you a question?",
    "Could we go for a walk later?",
    "Could they help us with the move?",
    "Could he join us for dinner tonight?",
    "Could she recommend a good restaurant in the area?",
    "Could it rain later today?",
    "Could you give me a hand with this, please?",
    "Could I have a glass of water, please?",
    "Could we talk about this later?",
    "Could they lend us some money for a few days?",
    "Could he play the piano when he was younger?",
    "Could she send me the document by email?",
    "Could it get any colder outside?",
    "Could you teach me how to play chess, please?",
    "Could I leave work a little early today?",
    "Could we book a table for two, please?",
    "Could they attend the meeting tomorrow?",
    "Could he explain the concept in more detail?",
    "Could she meet us at the train station?",
    "Could it have been a mistake?",
    "Could you please turn down the music a bit?",
    "Could I take a look at your passport, please?",
    "Could we visit the museum tomorrow?",
    "Could they find their way back home?",
    "Could he drive us to the airport?",
    "Could she recommend a good book to read?",
    "Could it be dangerous to swim in this river?",
    "Could you lend me some money until next week?",
    "Could I have a word with you, please?",
    "Could we order some pizza for dinner?",
    "Could they fix the leak in the bathroom?",
    "Could he come to the party with us?",
    "Could she help me choose a gift for my friend?",
    "Could it be true that aliens exist?",
    "Could you show me how to use this software, please?",
    "Could I have a moment to think about it?",
    "Could we watch a movie tonight?",
    "Could they pick us up from the train station?",
    "Could he recommend a good restaurant in town?",
    "Could she explain the problem to us?",
    "Could it snow tonight?",
    "Could you please help me carry this?",
    "Should we go to the gym today?",
    "Should you call your boss back?",
    "Should they invite their neighbors to the party?",
    "Should he apologize to his friend?",
    "Should she take a break from work?",
    "Should it be raining like this in June?",
    "Should we take the train or the bus?",
    "Should you ask for a raise?",
    "Should they hire a professional to fix the roof?",
    "Should he buy the blue shirt?",
    "Should she try the new restaurant in town?",
    "Should it be this difficult to assemble the furniture?",
    "Should we plan a trip for the weekend?",
    "Should you take a day off to rest?",
    "Should they invest in stocks?",
    "Should he study abroad next semester?",
    "Should she wear a dress to the party?",
    "Should it be mandatory to wear a mask in public?",
    "Should we adopt a pet?",
    "Should you take a language course?",
    "Should they cancel the meeting due to the weather?",
    "Should he ask her out on a date?",
    "Should she learn to play an instrument?",
    "Should it be allowed to smoke in public places?",
    "Should we try a new recipe for dinner?",
    "Should you apologize to your friend?",
    "Should they donate money to charity?",
    "Should he quit his job and start a business?",
    "Should she take a yoga class?",
    "Should it be necessary to learn a second language?",
    "Should we buy a new car?",
    "Should you seek professional help?",
    "Should they organize a charity event?",
    "Should he pursue a career in art?",
    "Should she go to the doctor for a check-up?",
    "Should it be safe to travel during the pandemic?",
    "Should we start a garden?",
    "Should you attend the conference?",
    "Should they get a divorce?",
    "Should he learn to cook?",
    "Should she take a self-defense class?",
    "Should it be legal to own exotic animals?",
    "Should we volunteer at the local shelter?",
    "Should you quit smoking?",
    "Should they buy a new house?",
    "Should he ask for her hand in marriage?",
    "Should she take a photography class?",
    "Should it be mandatory to recycle?",
    "Should we go on a hike this weekend?",
    "Should you take a break from social media?", 
    "Must we attend the conference?",
    "Must you finish the report today?",
    "Must they work overtime?",
    "Must he wear a tie to the party?",
    "Must she arrive on time?",
    "Must it be done by tomorrow?",
    "Must we take the train?",
    "Must you pay in advance?",
    "Must they sign a waiver?",
    "Must he complete the task alone?",
    "Must she speak with the manager?",
    "Must it be so difficult?",
    "Must we follow the instructions?",
    "Must you attend the orientation?",
    "Must they pass a test?",
    "Must he submit a proposal?",
    "Must she make a reservation?",
    "Must it be so loud?",
    "Must we wait in line?",
    "Must you wear a helmet?",
    "Must they provide their own equipment?",
    "Must he take a vacation?",
    "Must she work from home?",
    "Must it be this way?",
    "Must we start over?",
    "Must you attend the meeting?",
    "Must they wear a uniform?",
    "Must he attend the ceremony?",
    "Must she take a break?",
    "Must it be so expensive?",
    "Must we use this software?",
    "Must you answer the phone?",
    "Must they arrive early?",
    "Must he take a course?",
    "Must she wear a mask?",
    "Must it be so hot?",
    "Must we take notes?",
    "Must you work on the weekend?",
    "Must they provide references?",
    "Must he speak another language?",
    "Must she take care of the children?",
    "Must it be approved?",
    "Must we wear business attire?",
    "Must you follow the rules?",
    "Must they pass a background check?",
    "Must he have experience?",
    "Must she work with a team?",
    "Must it be this color?",
    "Must we use this equipment?",
    "Must you travel for work?",       
    "Would you like some coffee?",
    "Would he be available for a meeting tomorrow?",
    "Would she prefer a window or aisle seat?",
    "Would it be possible to reschedule the appointment?",
    "Would we need to bring our own equipment?",
    "Would they be willing to help us out?",
    "Would you mind closing the window?",
    "Would he consider a different approach?",
    "Would she like to join us for lunch?",
    "Would it be alright if I ask a question?",
    "Would we be able to access the internet?",
    "Would they like to provide feedback?",
    "Would you mind passing me the salt?",
    "Would he need additional support?",
    "Would she be interested in attending the event?",
    "Would it be too much trouble to help us move the furniture?",
    "Would we have to sign a contract?",
    "Would they like to receive a copy of the report?",
    "Would you be able to drive us to the airport?",
    "Would he require any special accommodations?",
    "Would she prefer to meet in person or via video call?",
    "Would it be necessary to make a reservation?",
    "Would we be able to get a discount?",
    "Would they like to participate in the survey?",
    "Would you mind taking a look at this document?",
    "Would he like to order something else?",
    "Would she need any assistance with the project?",
    "Would it be advisable to seek legal advice?",
    "Would we be able to attend the workshop?",
    "Would they like to schedule a follow-up meeting?",
    "Would you prefer a different color?",
    "Would he benefit from additional training?",
    "Would she like to try the new menu item?",
    "Would it be possible to extend the deadline?",
    "Would we be able to get a refund?",
    "Would they like to provide a testimonial?",
    "Would you mind if we rescheduled the appointment?",
    "Would he be interested in collaborating with us?",
    "Would she need a different size?",
    "Would it be acceptable to submit the report tomorrow?",
    "Would we be able to use the facility?",
    "Would they like to learn more about the program?",
    "Would you like me to explain that again?",
    "Would he require any specific tools?",
    "Would she prefer to work alone?",
    "Would it be feasible to complete the project on time?",
    "Would we be able to present our findings?",
    "Would they be available for a phone call?",
    "Would you like to make a reservation?",
    "Would he like to offer any suggestions?",
    "Are you feeling okay?",
    "Is it going to rain today?",
    "Am I allowed to bring my dog?",
    "Are we there yet?",
    "Are they coming to the party?",
    "Is she really going to quit her job?",
    "Are you going to the gym later?",
    "Is he always this forgetful?",
    "Am I pronouncing this word correctly?",
    "Are you planning to travel abroad anytime soon?",
    "Am I interrupting something?",
    "Are you sure you want to do this?",
    "Are they going to offer you the job?",
    "Is she still angry with me?",
    "Are you going to finish your food?",
    "Am I the only one who thinks this is a bad idea?",
    "Is it true that you won the lottery?",
    "Are we going to see each other again?",
    "Is he the one who stole my phone?",
    "Are you going to help me with this project?",
    "Am I going to be late for the meeting?",
    "Are they serving vegetarian options?",
    "Is she a good singer?",
    "Are you enjoying the party?",
    "Is he from Spain?",
    "Are we on the same page?",
    "Am I supposed to bring a gift?",
    "Are they open on Sundays?",
    "Is she your girlfriend?",
    "Are you going to the concert tonight?",
    "Is he a reliable source of information?",
    "Are we making progress?",
    "Am I the only one who thinks this restaurant is overrated?",
    "Are they still dating?",
    "Is she the one who recommended this book?",
    "Are you ready for the presentation?",
    "Is he allergic to peanuts?",
    "Are we lost?",
    "Am I allowed to take pictures here?",
    "Are they going to announce the winner soon?",
    "Is she taller than you?",
    "Are you going to watch the new movie that just came out?",
    "Is he the one who wrote this article?",
    "Are we running out of time?",
    "Am I doing this right?",
    "Are they going to be okay?",    
    "Are you hungry?",
    "Is she your sister?",
    "Are they coming to the party?",
    "Am I interrupting something?",
    "Is it hot outside?",
    "Are we there yet?",
    "Is he a good singer?",
    "Was she happy with the gift?",
    "Are you enjoying the book?",
    "Am I supposed to do that?",
    "Are they going on vacation?",
    "Is it time to go already?",
    "Are we lost?",
    "Is he your boss?",
    "Are you feeling better?",
    "Are they from England?",
    "Is it difficult to learn a new language?",
    "Are we having salad for dinner?",
    "Is she still at the office?",
    "Are you going to the gym later?",
    "Is he taller than you?",
    "Are they married?",
    "Is it raining outside?",
    "Are we allowed to bring our own drinks?",
    "Is she a good cook?",
    "Are you allergic to anything?",
    "Are they playing your favorite song?",
    "Is it a long way to the station?",
    "Are we meeting at the usual place?",
    "Is he a good listener?",
    "Are you going to the party tonight?",
    "Is she going to the conference?",
    "Are they coming to the meeting?",
    "Is it worth the price?",    
    "Were they happy with the results?",
    "Were you sick last week?",
    "Were you at the party last Saturday?",
    "Were you surprised by the news?",
    "Were you able to finish your homework on time?",
    "Were you excited to see your old friends?",
    "Were we able to catch the train?",
    "Was it informative?",
    "Were you satisfied with your exam score?",
    "Were you able to get enough rest?",
    "Was it clean and comfortable?",
    "Was it worth the hype?",
    "Were you nervous before your presentation?",
    "Was it interesting?",
    "Was it fun?",
    "Were you able to find the information you needed?",
    "Was it worth the ticket price?",
    "Were you surprised by the ending of the movie?",
    "Was it too loud?",
    "Were you able to get a good night's sleep?",
    "Was the performance well-received by the audience?",
    "Were you surprised by the election results?",
    "Was the basketball game exciting?",
    "Were you able to understand the instructions?",
    "Were you pleased with the outcome?",
    "Was it successful?",
    "Were they impressed by the architecture of the building?",
    "Were you able to finish your project on time?",
    "Were you happy with your grades?",
    "Were we successful?",
    "Were you able to meet your deadline?",
    "Do you like to exercise in the morning?",
    "Does she enjoy cooking new recipes?",
    "Do they study together for their exams?",
    "Do we need to submit the report today?",
    "Do I have enough time to finish this task?",
    "Does he always wear a suit to work?",
    "Do you like to go out for drinks on weekends?",
    "Do they have any plans for the summer?",
    "Do you need any help with the project?",
    "Does she listen to music while working?",
    "Do they prefer tea or coffee in the morning?",
    "Do we need to make reservations for the restaurant?",
    "Do you know how to play the guitar?",
    "Does he have a favorite TV show?",
    "Do they go on vacation every year?",
    "Do I need to bring my own laptop to the meeting?",
    "Do they live in the same city as you?",
    "Do they have a dog?",
    "Do you want to watch a movie tonight?",
    "Does she speak any other languages besides English?",
    "Do they like to cook their own meals?",
    "Do we need to leave early to avoid traffic?",
    "Do you enjoy reading books?",
    "Does he have any hobbies?",
    "Do they celebrate birthdays with a party?",
    "Do I need to wear a uniform to work?",
    "Do they have a good sense of humor?",
    "Do they usually work on weekends?",
    "Do you like to listen to podcasts?",
    "Does she have a favorite author?",
    "Do they live in a house or an apartment?",
    "Do we need to bring our own towels to the beach?",
    "Did you finish your homework last night?",
    "Did he watch the game on TV?",
    "Did she go to the gym this morning?",
    "Did they invite you to the party?",
    "Did we meet at the conference last year?",
    "Did you guys have fun on your trip?",
    "Did you follow the recipe for the cake?",
    "Did she enjoy the movie we watched last night?",
    "Did he ask for your opinion?",
    "Did you remember to lock the door before leaving?",
    "Did they play outside yesterday?",
    "Did he forget his wallet at home?",
    "Did they like the gift you gave them?",
    "Did she finish the project on time?",
    "Did you go to the concert last night?",
    "Did he take his medicine this morning?",
    "Did she buy the dress she saw at the store?",
    "Did they finish their meal at the restaurant?",
    "Did you take the bus to work today?",
    "Did he read the article you sent him?",
    "Did she listen to the podcast you recommended?",
    "Did they learn anything new in class today?",
    "Did you watch the sunset at the beach?",
    "Did he have a good time at the party?",
    "Did she practice the piano this afternoon?",
    "Did they finish their homework before dinner?",
    "Did you see the new movie in theaters?",
    "Did he pass the test?",
    "Did she apply for the job at the company?",
    "Did they enjoy the concert last night?",
    "Did you try the new restaurant downtown?",
    "Did he fix the leaking faucet in the bathroom?",
    "Did she call her friend back?",
    "Did they finish the crossword puzzle in the newspaper?",
    "Did you visit the museum on your trip?",
    "Did he clean his room this weekend?",
    "Did she dance at the party last night?",
    "Did they finish building the treehouse?",
    "Did you enjoy the play at the theater?",
    "Did he drive to the meeting this morning?",
    "Did she solve the riddle correctly?",
    "Did they find the missing key?",
    "Did you read the book I recommended?",
    "Did he finish the project before the deadline?",
    "Did she understand the instructions clearly?",
    "Did they participate in the marathon last month?",
    "Did you try the new coffee blend?",
    "Did he paint the living room walls over the weekend?",
    "Did she buy the plane tickets for the trip?",
    "Have you eaten breakfast yet?",
    "Has he finished his work for the day?",
    "Has she gone to the grocery store?",
    "Have they seen the new movie in theaters?",
    "Have we visited that museum before?",
    "Have you guys ever been to Europe?",
    "Have you learned any new skills recently?",
    "Has he studied for the exam?",
    "Has she finished reading the book?",
    "Has he ever traveled abroad?",
    "Have you ever tried skydiving?",
    "Have they played outside today?",
    "Has he forgotten his password again?",
    "Have they decided on a vacation destination?",
    "Has she practiced the guitar this week?",
    "Have you been to the beach lately?",
    "Has he taken his medicine today?",
    "Has she bought a new dress for the party?",
    "Have they finished their project on time?",
    "Have you taken a cooking class before?",
    "Has he read the article in the magazine?",
    "Has she listened to the new album?",
    "Have they met their sales quota for the month?",
    "Have you seen the latest episode of your favorite show?",
    "Has he had a good day so far?",
    "Has she studied for the upcoming exam?",
    "Have they finished their chores for the day?",
    "Have you tried the new restaurant in town?",
    "Has he passed the driver's test yet?",
    "Has she applied for the job at the company?",
    "Have they enjoyed the trip so far?",
    "Have you read any good books lately?",
    "Has he fixed the broken door yet?",
    "Has she called her friend back?",
    "Have they completed the online course?",
    "Have you visited the city before?",
    "Has he cleaned his room this week?",
    "Has she danced at the party last night?",
    "Have they finished building the sandcastle?",
    "Have you seen the Broadway show before?",
    "Has he driven to work today?",
    "Has she solved the puzzle correctly?",
    "Have they found the lost keys?",
    "Have you finished your work for the day?",
    "Has he submitted his report on time?",
    "Has she understood the instructions clearly?",
    "Have they participated in the charity event?",
    "Have you tried the new cocktail at the bar?",
    "Has he painted the bedroom walls yet?",
    "Has she booked the hotel for the vacation?",
    "Has it stopped raining outside?",
    "Has it been a year since we last saw each other?",,
    "Has it been difficult to adjust to the new job?",
    "Has it been a long day at work today?",
    "Has it been a while since you exercised?",
    "Has it taken you long to learn how to play the guitar?",
    "Has it been hard to make friends in a new city?",
    "Has it been a challenge to stick to your diet?",
    "Has it been a fun weekend so far?",
    "Has it been a year since you last traveled abroad?",
    "Has it been easy to adjust to the new time zone?",
    "Has it been a long time since you went on a date?",
    "Had you finished your homework before you went to bed last night?",
    "Had she seen the movie before you recommended it to her?",
    "Had they eaten lunch before the meeting started?",
    "Had you studied for the test before you took it?",
    "Had he visited the museum before it closed?",
    "Had she read the book before the discussion group met?",
    "Had you met her before the party last weekend?",
    "Had they completed the project before the deadline?",
    "Had he talked to his boss before he quit his job?",
    "Had she cleaned the house before the guests arrived?",
    "Had you visited that city before you moved there?",
    "Had they watched the show before it was canceled?",
    "Had you played that game before you bought it?",
    "Had he practiced the guitar before the concert?",
    "Had she written the report before the meeting?",
    "Had you seen that movie before it won an award?",
    "Had they finished the race before the rain started?",
    "Had he learned the song before the audition?",
    "Had she made the reservations before the restaurant filled up?",
    "Had you finished the book before the book club met?",
    "Had they fixed the car before the road trip?",
    "Had he read the email before he replied?",
    "Had she sent the package before the post office closed?",
    "Had you studied abroad before you graduated?",
    "Had they practiced the presentation before the conference?",
    "Had he watched the game before he heard the score?",
    "Had she cooked dinner before her family arrived?",
    "Had they finished the repairs before the customer arrived?",
    "Had he visited the park before the construction started?",
    "Had she finished the painting before the exhibition?",
    "Had you seen the band before they broke up?",
    "Had they visited the monument before the tour ended?",
    "Had he finished the book before he lent it to you?",
    "Had she completed the assignment before the due date?",
    "Had you arrived at the airport before the flight departed?",
    "Had they attended the lecture before the professor canceled?",
    "Had he cooked the meal before the guests arrived?",
    "Had she rehearsed the dance before the performance?",
    "Had you visited the museum before the renovation?",
    "Had they read the article before the discussion?",
    "Had he taken the medicine before the symptoms subsided?",
    "Had she filed the paperwork before the deadline?",
    "Had you seen the play before it closed?",
    "Had they finished the construction before the inspection?",
    "Had he completed the training before the job started?",
    "Had she written the poem before the contest?",
    "Had you prepared for the interview before the appointment?",
    "Had they finished the homework before the class started?",
    "Had he finished the project before the team meeting?",
    "Had it already stopped working by the time you got there?",
    "Had it been a long time since you last saw each other?",
    "Had it been a mistake to trust him in the first place?",
    "Had it been a successful event before the unexpected happened?",
    "Had it been a busy day for the team before they finally finished the project?",
    "Had it been snowing heavily before the roads were closed?",
    "Had it been an unexpected turn of events before everything went wrong?",
    "Had it been a productive day before the system crashed?",
    "Will it be sunny tomorrow?",
    "Will it be too late to apologize?",
    "Will it be a busy day at the office?",
    "Will it be easy to learn a new language?",
    "Will it be a good idea to invest in that company?",
    "Will it be worth the effort in the end?",
    "Will it be possible to finish the project on time?",
    "Will it be a difficult task to complete?",
    "Will he be able to finish the race on time?",
    "Will she be attending the conference next week?",
    "Will they be able to solve the problem before the deadline?",
    "Will we be having a meeting tomorrow morning?",
    "Will it be raining later today?",
    "Will you be able to join us for dinner tonight?",
    "Will they be able to find a new place to live before the end of the month?",
    "Will we be able to finish the project before the end of the quarter?",
    "Will he be taking the bus to work tomorrow?",
    "Will she be studying for the exam all weekend?",
    "Will they be having a party for their anniversary?",
    "Will we be traveling to Europe next summer?",
    "Will it be necessary to hire more employees?",
    "Will you be able to finish the report by the end of the day?",
    "Will he be working overtime this week?",
    "Will she be starting a new job next month?",
    "Will they be visiting their grandparents next weekend?",
    "Will we be celebrating Christmas with the whole family this year?",
    "Will he be watching the game on TV tonight?",
    "Will she be cooking dinner for us later?",
    "Will they be presenting their findings at the conference?",
    "Will we be taking a break from work next week?",
    "Will it be necessary to reschedule the meeting?",
    "Will you be running the marathon next year?",
    "Will he be fixing the car this weekend?",
    "Will she be performing in the play next month?",
    "Will they be volunteering at the shelter next Saturday?",
    "Will we be having a barbecue for the Fourth of July?",
    "Will he have finished the project by the end of the week?",
    "Will she have graduated from college by next year?",
    "Will they have completed the training by the time they start the new job?",
    "Will we have traveled to all the countries on our bucket list by the time we retire?",
    "Will it have been two years since we moved into our new house?",
    "Will you have learned how to play the piano by the end of the year?",
    "Will he have saved enough money for the down payment by the time they find a new house?",
    "Will she have written her first novel by the time she turns 40?",
    "Will they have planted the garden by the time the weather gets warmer?",
    "Will we have celebrated our 50th wedding anniversary by the time we retire?",
    "Will he have found a new job by the end of the month?",
    "Will she have finished the renovation project by the time the guests arrive?",
    "Will they have saved enough money for their dream vacation by next summer?",
    "Will we have completed all the tasks on our to-do list by the end of the day?",
    "Will it have been a year since we started our own business?",
    "Will you have finished reading that book by the time the movie comes out?",
    "Will he have repaired the roof before the rainy season starts?",
    "Will she have taken all the necessary classes by the time she applies for the job?",
    "Will they have reached their fitness goals by the end of the year?",
    "Will we have learned a new skill by the time we go on our next adventure?",
    "Will he have finished writing his dissertation by the end of the semester?",
    "Will she have bought a new car by the time she graduates?",
    "Will they have moved into their new house by next month?",
    "Will we have completed the renovation project by the end of the year?",
    "Will it have been five years since we last saw each other?",
    "Will you have earned your degree by the time your parents visit?"
]

var item = items[Math.floor(Math.random()*items.length)];
document.getElementById("question").innerHTML = item;

var score = 0;
var foundPattern = false;

function checkAnswers() {
    const answer = document.getElementById("text").value.toLowerCase();
    const currentQuestion = document.getElementById("question").innerHTML;
    const patterns = [
      {question: 'Can you', answers: ["yes, i can", "no, i can't"]},
      {question: 'Can they', answers: ["yes, they can", "no, they can't"]},
      {question: 'Can we', answers: ["yes, we can", "no, we can't"]},
      {question: 'Can I', answers: ["yes, you can", "no, you can't"]},
      {question: 'Can she', answers: ["yes, she can", "no, she can't"]},
      {question: 'Can he', answers: ["yes, he can", "no, he can't"]},
      {question: 'Can it', answers: ["yes, it can", "no, it can't"]},
      {question: 'Could you', answers: ["yes, i could", "no, i couldn't"]},
      {question: 'Could they', answers: ["yes, they could", "no, they couldn't"]},
      {question: 'Could we', answers: ["yes, we could", "no, we couldn't"]},
      {question: 'Could I', answers: ["yes, you could", "no, you couldn't"]},
      {question: 'Could she', answers: ["yes, she could", "no, she couldn't"]},
      {question: 'Could he', answers: ["yes, he could", "no, he couldn't"]},
      {question: 'Could it', answers: ["yes, it could", "no, it couldn't"]},
      {question: 'Should you', answers: ["yes, i should", "no, i shouldn't"]},
      {question: 'Should they', answers: ["yes, they should", "no, they shouldn't"]},
      {question: 'Should we', answers: ["yes, we should", "no, we shouldn't"]},
      {question: 'Should I', answers: ["yes, you should", "no, you shouldn't"]},
      {question: 'Should she', answers: ["yes, she should", "no, she shouldn't"]},
      {question: 'Should he', answers: ["yes, he should", "no, he shouldn't"]},
      {question: 'Should it', answers: ["yes, it should", "no, it shouldn't"]},
      {question: 'Must you', answers: ["yes, i must", "no, i mustn't"]},
      {question: 'Must they', answers: ["yes, they must", "no, they mustn't"]},
      {question: 'Must we', answers: ["yes, we must", "no, we mustn't"]},
      {question: 'Must I', answers: ["yes, you must", "no, you mustn't"]},
      {question: 'Must she', answers: ["yes, she must", "no, she mustn't"]},
      {question: 'Must he', answers: ["yes, he must", "no, he mustn't"]},
      {question: 'Must it', answers: ["yes, it must", "no, it mustn't"]},
      {question: 'Would you', answers: ["yes, i would", "no, i wouldn't"]},
      {question: 'Would they', answers: ["yes, they would", "no, they wouldn't"]},
      {question: 'Would we', answers: ["yes, we would", "no, we wouldn't"]},
      {question: 'Would I', answers: ["yes, you would", "no, you wouldn't"]},
      {question: 'Would she', answers: ["yes, she would", "no, she wouldn't"]},
      {question: 'Would he', answers: ["yes, he would", "no, he wouldn't"]},
      {question: 'Would it', answers: ["yes, it would", "no, it wouldn't"]}, 
      {question: 'Are you', answers: ["yes, i am", "no, i am not"]},
      {question: 'Are they', answers: ["yes, they are", "no, they aren't"]},
      {question: 'Are we', answers: ["yes, we are", "no, we aren't"]},
      {question: 'Am I', answers: ["yes, you are", "no, you aren't"]},
      {question: 'Is she', answers: ["yes, she is", "no, she isn't"]},
      {question: 'Is he', answers: ["yes, he is", "no, he isn't"]},
      {question: 'Is it', answers: ["yes, it is", "no, it isn't"]},
      {question: 'Were you', answers: ["yes, i was", "no, i wasn't"]},
      {question: 'Were they', answers: ["yes, they were", "no, they weren't"]},
      {question: 'Were we', answers: ["yes, we were", "no, we weren't"]},
      {question: 'Was I', answers: ["yes, you were", "no, you weren't"]},
      {question: 'Was she', answers: ["yes, she was", "no, she wasn't"]},
      {question: 'Was he', answers: ["yes, he was", "no, he wasn't"]},
      {question: 'Was it', answers: ["yes, it was", "no, it wasn't"]}, 
      {question: 'Do you', answers: ["yes, i do", "no, i dot"]},
      {question: 'Do they', answers: ["yes, they do", "no, they don't"]},
      {question: 'Do we', answers: ["yes, we do", "no, we don't"]},
      {question: 'Do I', answers: ["yes, you do", "no, you don't"]},
      {question: 'Does she', answers: ["yes, she does", "no, she doesn't"]},
      {question: 'Does he', answers: ["yes, he does", "no, he doesn't"]},
      {question: 'Does it', answers: ["yes, it does", "no, it doesn't"]},
      {question: 'Did you', answers: ["yes, i did", "no, i didn't"]},
      {question: 'Did they', answers: ["yes, they did", "no, they didn't"]},
      {question: 'Did we', answers: ["yes, we did", "no, we didn't"]},
      {question: 'Did I', answers: ["yes, you did", "no, you didn't"]},
      {question: 'Did she', answers: ["yes, she did", "no, she didn't"]},
      {question: 'Did he', answers: ["yes, he did", "no, he didn't"]},
      {question: 'Did it', answers: ["yes, it did", "no, it didn't"]}, 
      {question: 'Have you', answers: ["yes, i have", "no, i haven't"]},
      {question: 'Have they', answers: ["yes, they have", "no, they haven't"]},
      {question: 'Have we', answers: ["yes, we have", "no, we haven't"]},
      {question: 'Have I', answers: ["yes, you have", "no, you haven't"]},
      {question: 'Has she', answers: ["yes, she has", "no, she hasn't"]},
      {question: 'Has he', answers: ["yes, he has", "no, he hasn't"]},
      {question: 'Has it', answers: ["yes, it has", "no, it hasn't"]},
      {question: 'Had you', answers: ["yes, i had", "no, i hadn't"]},
      {question: 'Had they', answers: ["yes, they had", "no, they hadn't"]},
      {question: 'Had we', answers: ["yes, we had", "no, we hadn't"]},
      {question: 'Had I', answers: ["yes, you had", "no, you hadn't"]},
      {question: 'Had she', answers: ["yes, she had", "no, she hadn't"]},
      {question: 'Had he', answers: ["yes, he had", "no, he hadn't"]},
      {question: 'Had it', answers: ["yes, it had", "no, it hadn't"]}, 
      {question: 'Will you', answers: ["yes, i will", "no, i won't"]},
      {question: 'Will they', answers: ["yes, they will", "no, they won't"]},
      {question: 'Will we', answers: ["yes, we will", "no, we won't"]},
      {question: 'Will I', answers: ["yes, you will", "no, you won't"]},
      {question: 'Will she', answers: ["yes, she will", "no, she won't"]},
      {question: 'Will he', answers: ["yes, he will", "no, he won't"]},
      {question: 'Will it', answers: ["yes, it will", "no, it won't"]},   
    ];

    for (let i = 0; i < patterns.length; i++) {
      if (currentQuestion.includes(patterns[i].question) && patterns[i].answers.includes(answer)) {
        foundPattern = true;
        break;
      } else { 
        document.getElementById("message").innerHTML = "Respuesta incorrecta";
        document.getElementById("text").value = "";
      }
    }

      if (foundPattern) {
        score++;
        var item = items[Math.floor(Math.random()*items.length)];
        document.getElementById("question").innerHTML = item;
        document.getElementById("score").innerHTML = score;
        document.getElementById("message").innerHTML = "Responde estas preguntas";
        document.getElementById("text").value = "";
        foundPattern = false;
      } else {
        score = 0;
        document.getElementById("score").innerHTML = score;
      }
    }
  

  /* old code
  for (let i = 0; i < patterns.length; i++) {
      if (currentQuestion.includes(patterns[i].question) && patterns[i].answers.includes(answer)) {
        score++;
        var item = items[Math.floor(Math.random()*items.length)];
        document.getElementById("question").innerHTML = item;
        document.getElementById("score").innerHTML = score;
        document.getElementById("message").innerHTML = message;
        document.getElementById("text").value = "";
        break;
      } else {
        document.getElementById("message").innerHTML = "Respuesta incorrecta"
        document.getElementById("text").value = "";
      }
    }
  }
 */